--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

-- Started on 2021-08-31 22:10:06 EDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 16395)
-- Name: studentregistration; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA studentregistration;


ALTER SCHEMA studentregistration OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 16402)
-- Name: COURSE; Type: TABLE; Schema: studentregistration; Owner: postgres
--

CREATE TABLE studentregistration."COURSE" (
    "ID" bigint NOT NULL,
    "NAME" text
);


ALTER TABLE studentregistration."COURSE" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16405)
-- Name: COURSE_ID_seq; Type: SEQUENCE; Schema: studentregistration; Owner: postgres
--

ALTER TABLE studentregistration."COURSE" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME studentregistration."COURSE_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999999999999
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16396)
-- Name: STUDENT; Type: TABLE; Schema: studentregistration; Owner: postgres
--

CREATE TABLE studentregistration."STUDENT" (
    "ID" bigint NOT NULL,
    "NAME" text
);


ALTER TABLE studentregistration."STUDENT" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16465)
-- Name: STUDENT_COURSE; Type: TABLE; Schema: studentregistration; Owner: postgres
--

CREATE TABLE studentregistration."STUDENT_COURSE" (
    student_id bigint NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE studentregistration."STUDENT_COURSE" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16431)
-- Name: STUDENT_ID_seq; Type: SEQUENCE; Schema: studentregistration; Owner: postgres
--

ALTER TABLE studentregistration."STUDENT" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME studentregistration."STUDENT_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999999999999
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16491)
-- Name: course_registration; Type: TABLE; Schema: studentregistration; Owner: postgres
--

CREATE TABLE studentregistration.course_registration (
    "ID" bigint NOT NULL,
    "STUDENT_ID" bigint NOT NULL,
    "COURSE_ID" bigint NOT NULL
);


ALTER TABLE studentregistration.course_registration OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16494)
-- Name: course_registration_ID_seq; Type: SEQUENCE; Schema: studentregistration; Owner: postgres
--

ALTER TABLE studentregistration.course_registration ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME studentregistration."course_registration_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999999999999
    CACHE 20
);


--
-- TOC entry 3285 (class 0 OID 16402)
-- Dependencies: 202
-- Data for Name: COURSE; Type: TABLE DATA; Schema: studentregistration; Owner: postgres
--

COPY studentregistration."COURSE" ("ID", "NAME") FROM stdin;
\.


--
-- TOC entry 3284 (class 0 OID 16396)
-- Dependencies: 201
-- Data for Name: STUDENT; Type: TABLE DATA; Schema: studentregistration; Owner: postgres
--

COPY studentregistration."STUDENT" ("ID", "NAME") FROM stdin;
\.


--
-- TOC entry 3288 (class 0 OID 16465)
-- Dependencies: 210
-- Data for Name: STUDENT_COURSE; Type: TABLE DATA; Schema: studentregistration; Owner: postgres
--

COPY studentregistration."STUDENT_COURSE" (student_id, course_id) FROM stdin;
\.


--
-- TOC entry 3289 (class 0 OID 16491)
-- Dependencies: 211
-- Data for Name: course_registration; Type: TABLE DATA; Schema: studentregistration; Owner: postgres
--

COPY studentregistration.course_registration ("ID", "STUDENT_ID", "COURSE_ID") FROM stdin;
\.


--
-- TOC entry 3296 (class 0 OID 0)
-- Dependencies: 203
-- Name: COURSE_ID_seq; Type: SEQUENCE SET; Schema: studentregistration; Owner: postgres
--

SELECT pg_catalog.setval('studentregistration."COURSE_ID_seq"', 1, false);


--
-- TOC entry 3297 (class 0 OID 0)
-- Dependencies: 204
-- Name: STUDENT_ID_seq; Type: SEQUENCE SET; Schema: studentregistration; Owner: postgres
--

SELECT pg_catalog.setval('studentregistration."STUDENT_ID_seq"', 1, false);


--
-- TOC entry 3298 (class 0 OID 0)
-- Dependencies: 212
-- Name: course_registration_ID_seq; Type: SEQUENCE SET; Schema: studentregistration; Owner: postgres
--

SELECT pg_catalog.setval('studentregistration."course_registration_ID_seq"', 1, false);


-- Completed on 2021-08-31 22:10:09 EDT

--
-- PostgreSQL database dump complete
--

